### ISSUE TITLE
Bot freezing

### ISSUE THREAD

**Issue by wizardofwhere** [Codaone/DEXBot#331]
## Expected Behavior
I start the bot using staggered strategy and it places trades til the base coin is consumed.

## Actual Behavior
If there is insufficient funds to meet all required buys based on the spread/ upper/lower limits It consumes all the base coin and then tries to place another buy.  This buy remains until more coins are deposited at which point it will continue to buy.  Perhaps the program could be altered to stop attempting to purchase if there are insufficient funds or until a sell is made.  Also when the market center changes, the bot doesn't appear to adjust the trades (is that because it incurs trade fees?). 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 10
  - OS: Windows

**Comment by MarkoPaasila** [comment]
Can you describe the situation in more detail? Which market, what upper and lower bounds, did you "allow instant fill", manual/auto center price, how big was the market spread when you began, how much of each asset did you have?

The strategy is supposed to use all funds in the account by making orders evenly over the whole buy-range and separately but evenly over the full sell-range. So did it start by placing orders at the extremes and then narrow down until orders started filling, so that all funds were consumed by placing orders that stayed and ones that filled, or did it consume all of the other asset in orders that filled immediately - leaving no orders open for that asset?

**Comment by wizardofwhere1** [comment]
It did use all the funds.  The market is bitcny/bts, mountain, spread 6%, increment 5%, allow instant fill, Lower bound 0.43498000, Upper bound 1.72731000.  It starts placing orders at the outer bounds and works its way in til it ran out of funds and appeared to freeze.  I added more funds and it continued on til it ran out of all funds again. No trade was made.  You can close this, I'll go back later and try again to see what happens to perhaps add more detail.  Thx

**Comment by joelvai** [comment]
I don't think it freezes, but the bot doesn't clear the last info text and shows it until something happens.
