### ISSUE TITLE
SO: suggestions for fallback logic

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#443]
When target spread is not reached for whatever reason, we have a fallback logic which cancels furthest buy or sell order to free funds for closer order. Analyzing trading history I observed that this behavior may not be always optimal. Shifting sell orders in some cases may cause selling asset cheaper than it was bought initially (observed with buy slope mode)

Suggestion: on the sell side, don't cancel furthest orders ever, instead just place closer sell order using available (not allocated) funds.

**Comment by MarkoPaasila** [comment]
This fallback was initially for the case that the initial calculations are wrong. They seem pretty good, so this new fallback is totally ok. The other case is if we are one-sided, and cp moves away. In that case it's a tradeoff. If we can only make tiny orders, it will take a long time to get properly going, but if we remove the last order and make big closer orders, then we are "losing money". I would still choose to lose money because the direction will change sooner or later, and then I will be properly in the game immediately. 

I don't know. It's a matter of choice I think. I'm not sure it's worth the effort.

**Comment by bitfag** [comment]
This fallback logic is currently being actively used when orders are partially-filled on both sides, that one of them became fully filled, the strategy basically don't have enough funds to replace PF order + place another closer order, so it needs to cancel furthest.

This #443 along with #444 and #432 fixes the problem, so fallback logic will be really fallback for some outstanding cases.

Starting with only QUOTE on falling market... I think it's good idea to sell some QUOTE manually.
