### ISSUE TITLE
Base Strategy Unit Test

### ISSUE THREAD

**Issue by thehapax** [Codaone/DEXBot#516]
assigned to bitProfessor but this strategy needs major refactoring.

**Comment by thehapax** [comment]
Assigned to bitProfessor

**Comment by PermieBTS** [comment]
https://github.com/bitprofessor

**Comment by bitfag** [comment]
Note to @bitprofessor: we most likely will use **pytest**, In the #530 your tests were used `unittest`.

**Comment by bitProfessor** [comment]
get it


| |
bitprofessor
|
|
bitprofessor@163.com
|
签名由网易邮箱大师定制


On 03/28/2019 15:52，Vladimir Kamarzin<notifications@github.com> wrote：

Note to @bitProfessor: we most likely will use pytest, In the #530 your tests were used unittest.

**Comment by PermieBTS** [comment]
We should use either unittest _or_ pytest.
So far unittest seems to have been used, and switching to pytest would mean redoing previous work.
I would like to minimise disruption so I would favour using unittest if it is sufficient to test DEXBot pre and post refactor to ensure it works as intended. 

Does pytests benefits warrent redoing previous tests?
@bitfag

**Comment by bitfag** [comment]
1. At first, we actually don't use `unittest`, we only have stub "tests/test.py" which has only one test to start plain WorkerInfrastructure. So we're don't need to do any refactoring, we're free to pick any framework.
2. There are tests for external feeds in the `tests/` directory, but they are just `print()` based tests, and needs to be refactored anyway to use test framework we will pick up.

Here is the some reasons to use pytest:

* Brief comparison of pytest and unittest. Pytest is absolute winner https://github.com/renzon/pytest-vs-unittest
* Good overview, though covers pytest advantages only partially https://blog.daftcode.pl/the-cleaning-hand-of-pytest-28f434f4b684
* Pytest is designed to be a simpler, easier-to-code alternative to unittest
* Unittest-based tests may take more time to implement because of class inheritance model we will need to use to combine fixtures. Pytest fixtures inheritance is easier to use that similar unittest OOP approach. You do not need to invent Mixins to do inheritance.
* Fixture scopes very easy to use. For example, you need one PostgreSQL server instance for your tests, not a new PG for each test. So you just defining postgres fixture as `session` fixture. This saves testsuite execution time.
* Pytest reports are easier to read and they are more informative. This saves time.
* With pytets `/tests/*` directory should not contain `__init.py__` files. Pytest tests are supposed to not import anything from `tests`. This approach is less error prone.
* With pytest it is easy to add custom command-line arguments, for example you want some additional control for testing like "skip long-running tests". With unittest it's impossible to do easy.
* Pytest offers easy-to-use parametrization of test functions and fixtures
* Pytest has a "marks" system: can be used to apply meta data to test functions (but not fixtures), which can then be accessed by fixtures or plugins.

**Comment by PermieBTS** [comment]
You've convinced me :)
pytest going forward please team

@thehapax @bitfag @bitProfessor

**Comment by bitProfessor** [comment]
Of course pytest is the best, but I need a week or so to switch the original unit test code to pytest.


On 03/29/2019 03:34, Vladimir Kamarzin wrote:
At first, we actually don't use unittest, we only have stub "tests/test.py" which has only one test to start plain WorkerInfrastructure. So we're don't need to do any refactoring, we're free to pick any framework.
There are tests for external feeds in the tests/ directory, but they are just print() based tests, and needs to be refactored anyway to use test framework we will pick up.

Here is the some reasons to use pytest:

Brief comparison of pytest and unittest. Pytest is absolute winner https://github.com/renzon/pytest-vs-unittest
Good overview, though covers pytest advantages only partially https://blog.daftcode.pl/the-cleaning-hand-of-pytest-28f434f4b684
Pytest is designed to be a simpler, easier-to-code alternative to unittest
Unittest-based tests may take more time to implement because of class inheritance model we will need to use to combine fixtures. Pytest fixtures inheritance is easier to use that similar unittest OOP approach. You do not need to invent Mixins to do inheritance.
Fixture scopes very easy to use. For example, you need one PostgreSQL server instance for your tests, not a new PG for each test. So you just defining postgres fixture as session fixture. This saves testsuite execution time.
Pytest reports are easier to read and they are more informative. This saves time.
With pytets /tests/* directory should not contain __init.py__ files. Pytest tests are supposed to not import anything from tests. This approach is less error prone.
With pytest it is easy to add custom command-line arguments, for example you want some additional control for testing like "skip long-running tests". With unittest it's impossible to do easy.
Pytest offers easy-to-use parametrization of test functions and fixtures
Pytest has a "marks" system: can be used to apply meta data to test functions (but not fixtures), which can then be accessed by fixtures or plugins.

**Comment by bitProfessor** [comment]
1、I hope that my testing framework will be able to automate the testing of all dexbot units in the future.So I wrote a test framework for each function.I have completed about 170 functional testing frameworks
2、There's nothing wrong with switching to pytest, it just takes a little time.
