### ISSUE TITLE
DexBot - King of the Hill - Bot trades with itself if spread is = 0

### ISSUE THREAD

**Issue by NemesisZAUK** [Codaone/DEXBot#668]
##Strategy
King of the Hill

## Expected Behavior
When spread = 0 then bot should stop trading.

## Actual Behavior
When spread = 0 bot continues to trade with itself.

**Comment by bitfag** [comment]
TODO: 
* add check for own buy/sell price crossing
* add test

**Comment by bitfag** [comment]
Fixing this brings a one question: what the bot should do if it detects it's order will cross the other side? I mean, it cannot place an order on-top because it will cross. If the bot will place an order one step before  crossing, it will not be on top, this may appear to the user as bot working incorrectly not placing a top order.

I'm thinking about adding a warning like "Cannot place top xxx order because it will cross the other side; increase your order size to lower price step".

**Comment by PermieBTS** [comment]
Adding a warning is a good solution

**Comment by fractalnode** [comment]
> Fixing this brings a one question: what the bot should do if it detects it's order will cross the other side? I mean, it cannot place an order on-top because it will cross. If the bot will place an order one step before crossing, it will not be on top, this may appear to the user as bot working incorrectly not placing a top order.
> 
> I'm thinking about adding a warning like "Cannot place top xxx order because it will cross the other side; increase your order size to lower price step".

imo it is worth adding a minimum spread to the configuration

**Comment by bitfag** [comment]
Totally agree, minimum allowed spread is good idea. Please open a separate issue. Because of market fee, there is always aome minimal profitable spread. Crossing it means taking some loss.
