### ISSUE TITLE
KOTH ignores margin position

### ISSUE THREAD

**Issue by froooze** [Codaone/DEXBot#677]
## Expected Behavior
Respect margin position as order for KOTH

## Actual Behavior
Margin Position is ignored 

  - Version: 0.15.5
  - OS: Ubuntu Server 18.04

**Comment by PermieBTS** [comment]
Do you mean margin calls of other users?

**Comment by froooze** [comment]
> Do you mean margin calls of other users?

yes

**Comment by bitfag** [comment]
The problem is that `market.orderbook()` call doesn't have margin call positions, it's being discussed here https://github.com/bitshares/bitshares-core/issues/1958

Also, `get_call_orders()` RPC call doesn't have a proper call price, it's always 1:1
```
[{'id': '1.8.118282',
  'borrower': '1.2.453767',
  'collateral': '4852744343',
  'debt': 11827951,
  'call_price': {'base': {'amount': 1, 'asset_id': '1.3.0'},
   'quote': {'amount': 1, 'asset_id': '1.3.121'}},
  'target_collateral_ratio': 1600}]
```

But we're don't need this `call_price` anyway, because margin call will happen at `settlement_price / maximum_short_squeeze_ratio` price.

**Comment by bitfag** [comment]
* [ ] Add test to simulate margin call order and check KOTH behavior
