### ISSUE TITLE
Relative orders multiple workers on same account balance logic clarification

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#691]
#434 adds two new worker params "operational percent BASE" and "operational percent QUOTE" to define which part of balance the worker should use.

For Relative Orders, I don't think the worker should obey this setting. This would allow for the following setup:
* 1 SO worker with 49% BASE
* 1 SO worker with 50% BASE
* 1 RO worker with 1% BASE and relative order size say 10%

Despite the RO worker formally should be limited by 1% of total BASE, it could use all unallocated BASE balance (not in orders).

This is implicit logic which I don't like, but it's probably expected logic too.

**Comment by PermieBTS** [comment]
So you are proposing to change this logic to to be ignored by RO?

Woudl this be the only change needed? To add an exception such that RO doesn't obey that logic?

**Comment by bitfag** [comment]
This is a current behavior of RO, no changes needed. RO uses free balance (not in orders).

**Comment by fractalnode** [comment]
Today was a day when I wanted to try the operational_percent parameter for RO and it turned out that it did not work and that is why I found this thread.
Today I just wanted to set up the portfolio in such a way that:
AAA 25%
BBB 25%
CCC 50%

For this reason
AAA / BBB works on automatic allocation settings
but
AAA / CCC
BBB / CCC
were to work with a 50% allocation for CCC

It seems to me that these two parameters could be the logical basis for balancing assets in portfolio #685
