### ISSUE TITLE
Percentage allocation ignorred

### ISSUE THREAD

**Issue by froooze** [Codaone/DEXBot#712]
## Expected Behavior
Quote and Base Asset allocation in percentage should work with two RO-Bots

## Actual Behavior
Two RO-Bots with BTS/A and BTS/B trading pair. 

Quote: 50%
Base: 100% 

Both bots use 100% of the BTS and not 50%, like it should be.

## Specifications
  - Version: 0.17.5
  - OS: Ubuntu Server 18.04

**Comment by bitfag** [comment]
Yes, it was done intentionally, see #691 for discussion, but maybe it's a not fully good idea.

**Comment by fractalnode** [comment]
Today was a day when I wanted to try the operational_percent parameter for RO and it turned out that it did not work and that is why I found this thread.
Today I just wanted to set up the portfolio in such a way that:
AAA 25%
BBB 25%
CCC 50%

For this reason
AAA / BBB works on automatic allocation settings
but
AAA / CCC
BBB / CCC
were to work with a 50% allocation for CCC

It seems to me that these two parameters could be the logical basis for balancing assets in portfolio #685
