### ISSUE TITLE
DEXBot Crash

### ISSUE THREAD

**Issue by NemesisZAUK** [Codaone/DEXBot#713]
**DEXBot ver: 0.17.8**

- DEXBot exits without error when an existing worker is modified.
- DEXBot exits without error on creation of new worker.

Anyone know of a solution?

Other info:
DEXBot is being run on an HP server running Windows 10. It does not share this platform with any other applications and is not run on a VM. 
DEXBot has historically run on this config since the 1st versions of DEXBot.

**Comment by bitfag** [comment]
In version 0.17.8 dexbot-gui.exe exists with

> Back to parent (RC: -1073741819)

Same bug reported for pyinstaller https://github.com/pyinstaller/pyinstaller/issues/4550

Recent version 0.18.1 (which uses the same pyinstaller version 3.4) works fine. It's possible that the bug was caused by some 3rd party dependencies pulled at build time.
